function plot_SK_mu(u1, sim)
subplot(3,3,1)
sk1 = pp_check_obs_sk(u1,sim,tapas_sutton_k1_binary_sd01_config, tapas_sutton_k1_binary_optimal_config)
m1 = round(mean(sk1),3)
s1 = round(std(sk1),3)
title("0.1      "+"mean = "+ m1 + "              sd ="+ s1)
subplot(3,3,2)
sk5 = pp_check_obs_sk(u1,sim,tapas_sutton_k1_binary_sd05_config, tapas_sutton_k1_binary_optimal_config)
m1 = round(mean(sk5),3)
s1 = round(std(sk5),3)
title("0.2      "+"mean = "+ m1 + "              sd ="+ s1)
subplot(3,3,3)
sk10 = pp_check_obs_sk(u1,sim,tapas_sutton_k1_binary_sd1_config, tapas_sutton_k1_binary_optimal_config)
m1 = round(mean(sk10),3)
s1 = round(std(sk10),3)
title("0.3      "+"mean = "+ m1 + "              sd ="+ s1)
subplot(3,3,4)
sk20 = pp_check_obs_sk(u1,sim,tapas_sutton_k1_binary_sd2_config, tapas_sutton_k1_binary_optimal_config)
m1 = round(mean(sk20),3)
s1 = round(std(sk20),3)
title("0.4      "+"mean = "+ m1 + "              sd ="+ s1)
subplot(3,3,5)
